export const img = {
  cactusFooter: `${process.env.PUBLIC_URL}/assets/img/cactus_footer.png`,
  desertFooter: `${process.env.PUBLIC_URL}/assets/img/desert_footer.png`,
  leafFooer: `${process.env.PUBLIC_URL}/assets/img/leaf_footer.png`,
  footerImg: `${process.env.PUBLIC_URL}/assets/img/footer.png`,
  header: `${process.env.PUBLIC_URL}/assets/img/header.png`,
  leafLeftHeader: `${process.env.PUBLIC_URL}/assets/img/leaf_left.png`,
  leafRightHeader: `${process.env.PUBLIC_URL}/assets/img/leaf_right_header.png`,
  logoHeader: `${process.env.PUBLIC_URL}/assets/img/logo_header.png`,
  logoLogin: `${process.env.PUBLIC_URL}/assets/img/logo_login.png`,
  womanBook: `${process.env.PUBLIC_URL}/assets/img/woman_book.png`,
  woman: `${process.env.PUBLIC_URL}/assets/img/woman.png`,
  kakaoIcon: `${process.env.PUBLIC_URL}/assets/img/kakaotalk.png`,
  notPost: `${process.env.PUBLIC_URL}/assets/img/post_not.png`,
  banner1: `${process.env.PUBLIC_URL}/assets/img/banner1.png`,
  banner2: `${process.env.PUBLIC_URL}/assets/img/banner2.png`,
  banner3: `${process.env.PUBLIC_URL}/assets/img/banner3.png`,
  level: [
    `${process.env.PUBLIC_URL}/assets/img/level0.png`,
    `${process.env.PUBLIC_URL}/assets/img/level1.png`,
    `${process.env.PUBLIC_URL}/assets/img/level2.png`,
    `${process.env.PUBLIC_URL}/assets/img/level3.png`,
    `${process.env.PUBLIC_URL}/assets/img/level4.png`,
  ],
  rank: [
    `${process.env.PUBLIC_URL}/assets/img/rank0.png`,
    `${process.env.PUBLIC_URL}/assets/img/rank1.png`,
    `${process.env.PUBLIC_URL}/assets/img/rank2.png`,
  ],
  training: [
    `${process.env.PUBLIC_URL}/assets/img/word.jpeg`,
    `${process.env.PUBLIC_URL}/assets/img/self.jpeg`,
    `${process.env.PUBLIC_URL}/assets/img/transcription.jpeg`,
    `${process.env.PUBLIC_URL}/assets/img/letter.png`,
  ],

  bannerImage: `${process.env.PUBLIC_URL}/assets/img/bannerImage.png`,
  bannerImage2: `${process.env.PUBLIC_URL}/assets/img/bannerImage2.png`,
};
